from setuptools import setup, find_packages

setup(
    name="think-retriever",
    version="0.1.0",
    author="Your Name",
    author_email="you@example.com",
    description="Think-Retriever: An intelligent retrieval-augmented generation agent",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/your-org/think-retriever",
    license="MIT",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    python_requires=">=3.10",
    install_requires=[
        "torch>=2.1.0",
        "transformers>=4.40.0",
        "accelerate>=0.28.0",
        "trl>=0.9.0",
        "peft>=0.10.0",
        "rank-bm25>=0.2.2",
        "sentence-transformers>=2.7.0",
        "nltk>=3.8.1",
        "rouge-score>=0.1.2",
        "rapidfuzz>=3.6.0",
        "datasets>=2.18.0",
        "numpy>=1.26.0",
        "pandas>=2.2.0",
        "pyyaml>=6.0.1",
        "tqdm>=4.66.0",
        "jsonlines>=4.0.0",
        "rich>=13.7.0",
    ],
    extras_require={
        "dev": [
            "pytest>=8.1.0",
            "black>=24.3.0",
            "isort>=5.13.2",
            "mypy>=1.9.0",
        ],
        "gpu": ["faiss-gpu>=1.7.4"],
        "logging": ["wandb>=0.16.0"],
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
